<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20260207090806_create_user_table.cs" />
    <Compile Remove="Migrations\20260207090806_create_user_table.Designer.cs" />
    <Compile Remove="Migrations\20260207095014_add_role_column.cs" />
    <Compile Remove="Migrations\20260207095014_add_role_column.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.36" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.36">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.36" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CondoAmenitiesBooking.Application\CondoAmenitiesBooking.Application.csproj" />
    <ProjectReference Include="..\CondoAmenitiesBooking.Domain\CondoAmenitiesBooking.Domain.csproj" />
  </ItemGroup>

</Project>
